# Generated by Django 5.1.6 on 2025-02-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0005_subjectregistration_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subjectregistration",
            name="finish_date",
        ),
        migrations.RemoveField(
            model_name="subjectregistration",
            name="start_date",
        ),
    ]
